# Generated by Django 2.2.2 on 2021-08-29 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='船舶状态')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='公司名称')),
                ('addr', models.CharField(max_length=64, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='公司邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, verbose_name='执勤队名称')),
                ('addr', models.CharField(max_length=32, verbose_name='地址')),
                ('phone', models.CharField(max_length=12, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='船厂/码头名称')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Department', verbose_name='所属执勤队')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='工单名称')),
            ],
        ),
        migrations.CreateModel(
            name='PlanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='计划')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=16, verbose_name='真实姓名')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Company', verbose_name='代理公司')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Department', verbose_name='所属执勤队')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='拥有的所有角色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=32, verbose_name='中文名')),
                ('english_name', models.CharField(max_length=32, verbose_name='英文名')),
                ('nationality', models.CharField(max_length=16, verbose_name='国籍')),
                ('crew_detail', models.TextField(verbose_name='船员国籍和人数')),
                ('crew_total', models.PositiveIntegerField(verbose_name='船员总数')),
                ('goods', models.CharField(max_length=32, verbose_name='货物情况')),
                ('IMO', models.CharField(max_length=7, verbose_name='IMO')),
                ('MMSI', models.CharField(max_length=9, verbose_name='MMSI')),
                ('purpose', models.CharField(max_length=32, verbose_name='来港目的')),
                ('guns', models.IntegerField(choices=[(1, '无'), (2, '有')], default=1, verbose_name='枪支弹药')),
                ('last_port', models.CharField(max_length=32, verbose_name='上一港')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('status', models.IntegerField(blank=True, choices=[(0, '暂无'), (1, '在港'), (2, '离港')], default=0, null=True, verbose_name='是否在港')),
                ('port_in', models.CharField(blank=True, max_length=42, null=True, verbose_name='在港位置')),
                ('display', models.IntegerField(choices=[(1, '未删除'), (2, '删除')], default=1, verbose_name='是否显示')),
                ('boat_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.BoatStatus', verbose_name='船舶申请状态')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Location', verbose_name='船厂/码头')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='申报人')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_time', models.DateTimeField(verbose_name='计划时间')),
                ('next_port', models.CharField(blank=True, max_length=16, null=True, verbose_name='下一港口/泊位')),
                ('display', models.IntegerField(choices=[(1, '未删除'), (2, '删除')], default=1, verbose_name='是否显示')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('move_number', models.IntegerField(blank=True, null=True, verbose_name='移泊次数')),
                ('last_port', models.CharField(blank=True, max_length=25, null=True, verbose_name='上一次的位置')),
                ('apply', models.DateTimeField(auto_now_add=True, null=True, verbose_name='申报时间')),
                ('report', models.BooleanField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否为补报')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='web.UserInfo', verbose_name='代理')),
                ('boat_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.BoatStatus', verbose_name='船舶申请状态')),
                ('check_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_user', to='web.UserInfo', verbose_name='审核人')),
                ('last_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='web.Location', verbose_name='上一次位置')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Location', verbose_name='船厂/码头')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Order', verbose_name='工单')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Ship', verbose_name='船名')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.PlanStatus', verbose_name='船舶计划')),
            ],
        ),
    ]
