# Generated by Django 2.2.2 on 2021-08-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='report',
        ),
    ]
