# Generated by Django 2.2.2 on 2021-08-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='report',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否为补报'),
        ),
    ]
