# Generated by Django 2.2.2 on 2021-08-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_plan_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='report',
            field=models.IntegerField(choices=[(3, '否'), (4, '是')], default=3, verbose_name='是否为补报'),
        ),
    ]
