# Generated by Django 2.2.2 on 2021-08-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210321_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='next_port',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='下一港口/泊位'),
        ),
    ]
