# Generated by Django 2.2.2 on 2021-08-30 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_plan_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='事项')),
                ('content', models.TextField(verbose_name='内容')),
                ('file', models.FileField(upload_to='file')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.Ship')),
            ],
        ),
    ]
