# Generated by Django 2.2.2 on 2021-08-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_shipdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipdetail',
            name='ship',
        ),
        migrations.AlterField(
            model_name='shipdetail',
            name='file',
            field=models.FileField(upload_to='./file/'),
        ),
    ]
