# Generated by Django 2.2.2 on 2021-08-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_plan_apply_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='apply_time',
            new_name='apply',
        ),
    ]
