# Generated by Django 2.2.2 on 2021-08-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_shipdetail_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdetail',
            name='old_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
