# Generated by Django 2.2.2 on 2021-08-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_shipdetail_old_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdetail',
            name='note',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
    ]
