# Generated by Django 2.2.2 on 2021-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_shipdetail_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdetail',
            name='status',
            field=models.BooleanField(choices=[(0, '未完成'), (1, '完成')], default=0),
        ),
    ]
