# Generated by Django 2.2.2 on 2021-08-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_shipdetail_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipDetail',
        ),
    ]
