# Generated by Django 2.2.2 on 2021-09-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_delete_shipdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='公司/码头名称')),
                ('addr', models.CharField(max_length=64, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='公司邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='company_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.CompanyPort', verbose_name='所属船厂、码头'),
        ),
    ]
