# Generated by Django 2.2.2 on 2021-09-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210904_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='company_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Location', verbose_name='所属船厂、码头'),
        ),
        migrations.DeleteModel(
            name='CompanyPort',
        ),
    ]
