# Generated by Django 2.2.2 on 2021-09-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210904_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('last_port', models.CharField(max_length=16, null=True)),
                ('port_in', models.CharField(max_length=16, verbose_name='位置')),
                ('note', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.UserInfo')),
            ],
        ),
    ]
