# Generated by Django 2.2.2 on 2021-09-04 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_moveplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='事项')),
                ('content', models.TextField(verbose_name='内容')),
                ('file', models.FileField(upload_to='file/')),
                ('old_name', models.CharField(default='', max_length=50, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('note', models.TextField(null=True, verbose_name='备注')),
                ('status', models.BooleanField(choices=[(0, '未完成'), (1, '完成')], default=0)),
                ('ship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_detail', to='web.Ship')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.UserInfo')),
            ],
        ),
    ]
